// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzQ9sV0ymwa8HB_VU-CMNPSVAideyrbdg',
    appId: '1:954935895311:web:2471aa80e37bacea0dca7a',
    messagingSenderId: '954935895311',
    projectId: 'plaza-80235',
    authDomain: 'plaza-80235.firebaseapp.com',
    storageBucket: 'plaza-80235.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD537kwcZ3DphehLNXgLGiwKhNFvEALyQg',
    appId: '1:954935895311:android:beb5428d2a50d7a10dca7a',
    messagingSenderId: '954935895311',
    projectId: 'plaza-80235',
    storageBucket: 'plaza-80235.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0bOYIe5l_cxmSTpWADeFkc-c16EU9juU',
    appId: '1:954935895311:ios:a3eba1ef42e7a3430dca7a',
    messagingSenderId: '954935895311',
    projectId: 'plaza-80235',
    storageBucket: 'plaza-80235.appspot.com',
    iosClientId: '954935895311-klo3cf5sagm8g2i6o9078ov7n99v51mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonPlaza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0bOYIe5l_cxmSTpWADeFkc-c16EU9juU',
    appId: '1:954935895311:ios:a3eba1ef42e7a3430dca7a',
    messagingSenderId: '954935895311',
    projectId: 'plaza-80235',
    storageBucket: 'plaza-80235.appspot.com',
    iosClientId: '954935895311-klo3cf5sagm8g2i6o9078ov7n99v51mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonPlaza',
  );
}
